/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  anon_sym_param = 2,
  anon_sym_param_LBRACKin_RBRACK = 3,
  anon_sym_param_LBRACKout_RBRACK = 4,
  anon_sym_return = 5,
  anon_sym_brief = 6,
  anon_sym_file = 7,
  anon_sym_author = 8,
  sym__param = 9,
  anon_sym_AT = 10,
  sym_source_file = 11,
  sym__keyword_with_param = 12,
  sym__keyword_without_param = 13,
  sym_identifier_with_param = 14,
  sym_identifier_without_param = 15,
  sym_variable = 16,
  sym_doxygen = 17,
  aux_sym_source_file_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [anon_sym_param] = "param",
  [anon_sym_param_LBRACKin_RBRACK] = "param[in]",
  [anon_sym_param_LBRACKout_RBRACK] = "param[out]",
  [anon_sym_return] = "return",
  [anon_sym_brief] = "brief",
  [anon_sym_file] = "file",
  [anon_sym_author] = "author",
  [sym__param] = "_param",
  [anon_sym_AT] = "@",
  [sym_source_file] = "source_file",
  [sym__keyword_with_param] = "_keyword_with_param",
  [sym__keyword_without_param] = "_keyword_without_param",
  [sym_identifier_with_param] = "identifier_with_param",
  [sym_identifier_without_param] = "identifier_without_param",
  [sym_variable] = "variable",
  [sym_doxygen] = "doxygen",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [anon_sym_param] = anon_sym_param,
  [anon_sym_param_LBRACKin_RBRACK] = anon_sym_param_LBRACKin_RBRACK,
  [anon_sym_param_LBRACKout_RBRACK] = anon_sym_param_LBRACKout_RBRACK,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_brief] = anon_sym_brief,
  [anon_sym_file] = anon_sym_file,
  [anon_sym_author] = anon_sym_author,
  [sym__param] = sym__param,
  [anon_sym_AT] = anon_sym_AT,
  [sym_source_file] = sym_source_file,
  [sym__keyword_with_param] = sym__keyword_with_param,
  [sym__keyword_without_param] = sym__keyword_without_param,
  [sym_identifier_with_param] = sym_identifier_with_param,
  [sym_identifier_without_param] = sym_identifier_without_param,
  [sym_variable] = sym_variable,
  [sym_doxygen] = sym_doxygen,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_param] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_param_LBRACKin_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_param_LBRACKout_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brief] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_file] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_author] = {
    .visible = true,
    .named = false,
  },
  [sym__param] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__keyword_with_param] = {
    .visible = false,
    .named = true,
  },
  [sym__keyword_without_param] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier_with_param] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_without_param] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_doxygen] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead == 'a') ADVANCE(25);
      if (lookahead == 'b') ADVANCE(20);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ']') ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == ']') ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(1);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 28:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') SKIP(29);
      if (lookahead == '@') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '@') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_param);
      if (lookahead == '[') ADVANCE(12);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_param_LBRACKin_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_param_LBRACKout_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_brief);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_file);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_author);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__param);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 29},
  [4] = {.lex_state = 29},
  [5] = {.lex_state = 29},
  [6] = {.lex_state = 29},
  [7] = {.lex_state = 28},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 29},
  [13] = {.lex_state = 29},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_param] = ACTIONS(1),
    [anon_sym_param_LBRACKin_RBRACK] = ACTIONS(1),
    [anon_sym_param_LBRACKout_RBRACK] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_brief] = ACTIONS(1),
    [anon_sym_file] = ACTIONS(1),
    [anon_sym_author] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(8),
    [sym_identifier_with_param] = STATE(7),
    [sym_identifier_without_param] = STATE(9),
    [sym_doxygen] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_text] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      anon_sym_param,
    STATE(10), 1,
      sym__keyword_with_param,
    STATE(11), 1,
      sym__keyword_without_param,
    ACTIONS(11), 3,
      anon_sym_param_LBRACKin_RBRACK,
      anon_sym_param_LBRACKout_RBRACK,
      anon_sym_return,
    ACTIONS(13), 3,
      anon_sym_brief,
      anon_sym_file,
      anon_sym_author,
  [20] = 6,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_text,
    STATE(7), 1,
      sym_identifier_with_param,
    STATE(9), 1,
      sym_identifier_without_param,
    STATE(4), 2,
      sym_doxygen,
      aux_sym_source_file_repeat1,
  [40] = 6,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_text,
    ACTIONS(24), 1,
      anon_sym_AT,
    STATE(7), 1,
      sym_identifier_with_param,
    STATE(9), 1,
      sym_identifier_without_param,
    STATE(4), 2,
      sym_doxygen,
      aux_sym_source_file_repeat1,
  [60] = 2,
    ACTIONS(29), 1,
      anon_sym_AT,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      sym_text,
  [68] = 2,
    ACTIONS(33), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_text,
  [76] = 2,
    ACTIONS(35), 1,
      sym__param,
    STATE(13), 1,
      sym_variable,
  [83] = 1,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
  [87] = 1,
    ACTIONS(39), 1,
      sym_text,
  [91] = 1,
    ACTIONS(41), 1,
      sym__param,
  [95] = 1,
    ACTIONS(43), 1,
      sym_text,
  [99] = 1,
    ACTIONS(45), 1,
      sym_text,
  [103] = 1,
    ACTIONS(47), 1,
      sym_text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 68,
  [SMALL_STATE(7)] = 76,
  [SMALL_STATE(8)] = 83,
  [SMALL_STATE(9)] = 87,
  [SMALL_STATE(10)] = 91,
  [SMALL_STATE(11)] = 95,
  [SMALL_STATE(12)] = 99,
  [SMALL_STATE(13)] = 103,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doxygen, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doxygen, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doxygen, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doxygen, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_with_param, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_without_param, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_doxygen(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "doxygen",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
