/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_param = 1,
  anon_sym_param_LBRACKin_RBRACK = 2,
  anon_sym_param_LBRACKout_RBRACK = 3,
  anon_sym_params = 4,
  anon_sym_params_LBRACKin_RBRACK = 5,
  anon_sym_params_LBRACKout_RBRACK = 6,
  anon_sym_return = 7,
  anon_sym_returns = 8,
  anon_sym_brief = 9,
  anon_sym_file = 10,
  anon_sym_author = 11,
  anon_sym_authors = 12,
  anon_sym_license = 13,
  anon_sym_def = 14,
  anon_sym_deprecated = 15,
  anon_sym_copyright = 16,
  anon_sym_date = 17,
  anon_sym_fn = 18,
  sym_prefix = 19,
  sym_variable = 20,
  sym_text = 21,
  anon_sym_SPACE = 22,
  sym_source_file = 23,
  sym_with_params = 24,
  sym_text_only = 25,
  sym_doxygen = 26,
  aux_sym_source_file_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_param] = "param",
  [anon_sym_param_LBRACKin_RBRACK] = "param[in]",
  [anon_sym_param_LBRACKout_RBRACK] = "param[out]",
  [anon_sym_params] = "params",
  [anon_sym_params_LBRACKin_RBRACK] = "params[in]",
  [anon_sym_params_LBRACKout_RBRACK] = "params[out]",
  [anon_sym_return] = "return",
  [anon_sym_returns] = "returns",
  [anon_sym_brief] = "brief",
  [anon_sym_file] = "file",
  [anon_sym_author] = "author",
  [anon_sym_authors] = "authors",
  [anon_sym_license] = "license",
  [anon_sym_def] = "def",
  [anon_sym_deprecated] = "deprecated",
  [anon_sym_copyright] = "copyright",
  [anon_sym_date] = "date",
  [anon_sym_fn] = "fn",
  [sym_prefix] = "prefix",
  [sym_variable] = "variable",
  [sym_text] = "text",
  [anon_sym_SPACE] = " ",
  [sym_source_file] = "source_file",
  [sym_with_params] = "with_params",
  [sym_text_only] = "text_only",
  [sym_doxygen] = "doxygen",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_param] = anon_sym_param,
  [anon_sym_param_LBRACKin_RBRACK] = anon_sym_param_LBRACKin_RBRACK,
  [anon_sym_param_LBRACKout_RBRACK] = anon_sym_param_LBRACKout_RBRACK,
  [anon_sym_params] = anon_sym_params,
  [anon_sym_params_LBRACKin_RBRACK] = anon_sym_params_LBRACKin_RBRACK,
  [anon_sym_params_LBRACKout_RBRACK] = anon_sym_params_LBRACKout_RBRACK,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_returns] = anon_sym_returns,
  [anon_sym_brief] = anon_sym_brief,
  [anon_sym_file] = anon_sym_file,
  [anon_sym_author] = anon_sym_author,
  [anon_sym_authors] = anon_sym_authors,
  [anon_sym_license] = anon_sym_license,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_deprecated] = anon_sym_deprecated,
  [anon_sym_copyright] = anon_sym_copyright,
  [anon_sym_date] = anon_sym_date,
  [anon_sym_fn] = anon_sym_fn,
  [sym_prefix] = sym_prefix,
  [sym_variable] = sym_variable,
  [sym_text] = sym_text,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_source_file] = sym_source_file,
  [sym_with_params] = sym_with_params,
  [sym_text_only] = sym_text_only,
  [sym_doxygen] = sym_doxygen,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_param] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_param_LBRACKin_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_param_LBRACKout_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_params] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_params_LBRACKin_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_params_LBRACKout_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_returns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brief] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_file] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_author] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_authors] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_license] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deprecated] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_copyright] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_with_params] = {
    .visible = true,
    .named = true,
  },
  [sym_text_only] = {
    .visible = true,
    .named = true,
  },
  [sym_doxygen] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_identifier = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_identifier] = "identifier",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifier, 0},
    {field_identifier, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(62);
      ADVANCE_MAP(
        '@', 81,
        'a', 55,
        'b', 42,
        'c', 38,
        'd', 8,
        'f', 26,
        'l', 27,
        'p', 7,
        'r', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == ']') ADVANCE(64);
      END_STATE();
    case 3:
      if (lookahead == ']') ADVANCE(65);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(67);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(68);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(52);
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(77);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(76);
      if (lookahead == 'p') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(71);
      END_STATE();
    case 23:
      if (lookahead == 'g') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'h') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(49);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(37);
      if (lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(63);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(2);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'p') ADVANCE(59);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(3);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 55:
      if (lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 56:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 57:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 58:
      if (lookahead == 'u') ADVANCE(53);
      END_STATE();
    case 59:
      if (lookahead == 'y') ADVANCE(45);
      END_STATE();
    case 60:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 61:
      if (eof) ADVANCE(62);
      if (lookahead == '\n') SKIP(61);
      if (lookahead == '@') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0) ADVANCE(84);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_param);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == 's') ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_param_LBRACKin_RBRACK);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_param_LBRACKout_RBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_params);
      if (lookahead == '[') ADVANCE(31);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_params_LBRACKin_RBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_params_LBRACKout_RBRACK);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_return);
      if (lookahead == 's') ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_returns);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_brief);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_file);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_author);
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_authors);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_license);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_deprecated);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_copyright);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_date);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_prefix);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '@') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(85);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 61},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 61},
  [4] = {.lex_state = 61},
  [5] = {.lex_state = 61},
  [6] = {.lex_state = 61},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 60},
  [9] = {.lex_state = 61},
  [10] = {.lex_state = 60},
  [11] = {.lex_state = 61},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 61},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_param] = ACTIONS(1),
    [anon_sym_param_LBRACKin_RBRACK] = ACTIONS(1),
    [anon_sym_param_LBRACKout_RBRACK] = ACTIONS(1),
    [anon_sym_params] = ACTIONS(1),
    [anon_sym_params_LBRACKin_RBRACK] = ACTIONS(1),
    [anon_sym_params_LBRACKout_RBRACK] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_returns] = ACTIONS(1),
    [anon_sym_brief] = ACTIONS(1),
    [anon_sym_file] = ACTIONS(1),
    [anon_sym_author] = ACTIONS(1),
    [anon_sym_authors] = ACTIONS(1),
    [anon_sym_license] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_deprecated] = ACTIONS(1),
    [anon_sym_copyright] = ACTIONS(1),
    [anon_sym_date] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [sym_prefix] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(7),
    [sym_doxygen] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_prefix] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_with_params] = STATE(10),
    [sym_text_only] = STATE(11),
    [anon_sym_param] = ACTIONS(9),
    [anon_sym_param_LBRACKin_RBRACK] = ACTIONS(11),
    [anon_sym_param_LBRACKout_RBRACK] = ACTIONS(11),
    [anon_sym_params] = ACTIONS(9),
    [anon_sym_params_LBRACKin_RBRACK] = ACTIONS(11),
    [anon_sym_params_LBRACKout_RBRACK] = ACTIONS(11),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_returns] = ACTIONS(11),
    [anon_sym_brief] = ACTIONS(13),
    [anon_sym_file] = ACTIONS(13),
    [anon_sym_author] = ACTIONS(15),
    [anon_sym_authors] = ACTIONS(13),
    [anon_sym_license] = ACTIONS(13),
    [anon_sym_def] = ACTIONS(13),
    [anon_sym_deprecated] = ACTIONS(13),
    [anon_sym_copyright] = ACTIONS(13),
    [anon_sym_date] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      sym_prefix,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_text,
    STATE(4), 2,
      sym_doxygen,
      aux_sym_source_file_repeat1,
  [14] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_prefix,
    ACTIONS(26), 1,
      sym_text,
    STATE(4), 2,
      sym_doxygen,
      aux_sym_source_file_repeat1,
  [28] = 2,
    ACTIONS(31), 1,
      sym_prefix,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      sym_text,
  [36] = 2,
    ACTIONS(35), 1,
      sym_prefix,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym_text,
  [44] = 1,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
  [48] = 1,
    ACTIONS(39), 1,
      sym_variable,
  [52] = 1,
    ACTIONS(41), 1,
      sym_text,
  [56] = 1,
    ACTIONS(43), 1,
      sym_variable,
  [60] = 1,
    ACTIONS(45), 1,
      sym_text,
  [64] = 1,
    ACTIONS(47), 1,
      anon_sym_SPACE,
  [68] = 1,
    ACTIONS(49), 1,
      sym_text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 14,
  [SMALL_STATE(5)] = 28,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 44,
  [SMALL_STATE(8)] = 48,
  [SMALL_STATE(9)] = 52,
  [SMALL_STATE(10)] = 56,
  [SMALL_STATE(11)] = 60,
  [SMALL_STATE(12)] = 64,
  [SMALL_STATE(13)] = 68,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doxygen, 3, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doxygen, 3, 0, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doxygen, 5, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doxygen, 5, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_params, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_only, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_doxygen(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "doxygen",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
